config/routes.rb
Rails.application.routes.draw do
  root 'bio#index'
  
  get '/bio' => 'bio#index'
  get '/contact' => 'contact#new'
  get '/experience' => 'statics#experience'
  get '/microapps' => 'statics#microapps'
  get '/skills' => 'statics#skills'

  resources :contact, only:[ :create,:new ]

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/bio_controller.rb
class BioController < ApplicationController
end

app/controllers/contact_controller.rb
class ContactController < ApplicationController
  def new
    
  end

  def create
    @params = params[:contact]
    @name = params[:contact][:name]
    @msg = params[:contact][:msg]
    if params[:contact][:msg].blank? || params[:contact][:name].blank? 
      flash.now[:danger] = "Hay que rellenar nombre y mensaje "
      render 'new'
    else
      if !ContactMailer.contact_mailer(@name,@msg).deliver
        flash.now[:danger] = "Error al enviar el mensaje"
        render 'new'
      else
        flash[:success] = "Mensaje enviado correctamente"
        @params = nil
        redirect_to contact_path
      end
    end
  end
end

app/controllers/statics_controller.rb
class StaticsController < ApplicationController
  def home
    # => render html: '<h1>HOLAAA</h1>'
  end

  def experience
    
  end

  def microapps
    
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bio_helper.rb
module BioHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/statics_helper.rb
module StaticsHelper
end

app/views/bio/index.html.erb
<div id="bio">
  <%= image_tag 'jesusmlg_m.jpg',id: 'biophoto', class: 'img-responsive img-center img-circle' %>
<ul>
  <li><b>Name</b>: Jesús María Luis Gil</li>
  <li><b>Date of Birdth</b>: 09/08/1982</li>
  <li><b>Location</b>: Actually living in Badajoz (Spain) and trying to move out to Sevilla (Spain)</li>
  <li><b>Email:</b> jesusmlg@gmail.com</li>
  <li><b>GitHub:</b> <%= link_to 'https://github.com/jesusmlg' %></li> 
  <li><b>Web:</b> <%= link_to  'www.jesusmlg.com' %></li>
  <li><b>Linked-IN</b>: <%= link_to 'http://es.linkedin.com/in/jesuslg' %></li>
</ul>

<h3 class="text-center">EDUCATION</h3>

<table class="table">
  <tr>
    <th>Year</th>
    <th>Content</th>
  </tr>
  <tr>
    <td>
      2005 - 2003
    </td>
    <td>
      Systems administration (IES Claudio Moyano, Zamora)
    </td>
  </tr>
  <tr>
    <td>
      2006 - 2005 
    </td>
    <td>
      Master in networks and security (Cibernos Institute,  Madrid)
    </td>
  </tr>
  <tr>
    <td>
      2006
    </td>
    <td>
      NS1 and NS2 CNAPS of CCSP  Certification - Cisco Systems (Cibernos Institute,  Madrid)

    </td>
  </tr>
  <tr>
    <td>
      2011
    </td>
    <td>
      Course on SEO/SEM positioning and campaigns. 
    </td>
  </tr>
  <tr>
    <td>
      2012
    </td>
    <td>
      Course on the  JQuery framework, CSS and the Moodle e-learning platform
    </td>
  </tr>
  
</table>
</div>

 

app/views/contact/new.html.erb
  <% flash.each do |k,v| %>
    <div class="text-center img-rounded alert-<%= k %>"><%= v %></div>
  <% end %>

<div align="center" id="contact">
    <ul class="list-group">
        <%= form_for(:contact, url:{action: "create"},class: 'form-control' ) do |f|%>
          <li><%= f.label 'Name' , class: '' %></li>
          <li><%= f.text_field :name , value: @name ,class: "form-control" %></li>
          <li><%= f.label 'Message' %></li>
          <li><%= f.text_area :msg ,value: @msg, class: "form-control", rows: 6, cols: 40 %></li>
          <li><%= f.submit 'ENVIAR' , class: "btn btn-lg btn-danger" %></li>
       <% end %>
    </ul>
</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default navbar-fixed-top text-center">
  <div class="container-fluid ">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header ">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse " id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li id="bio"><%= link_to 'BIO', bio_path %></li>
        <li id="skills"><%= link_to 'SKILLS', skills_path %></li>
        <li id="experience"><%= link_to 'EXPERIENCE', experience_path %></li>
        <li id="microapps"><%= link_to 'MICROAPPS', microapps_path %></li>
        <li id="contact"><%= link_to 'CONTACT', contact_path %></li>       
      </ul>
      
      
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Jesús María Luis Gil - Web and Desktop Developer</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= favicon_link_tag 'favicon.ico' %>
  <%= csrf_meta_tags %>
</head>
<body>
  <nav><%= render partial: 'layouts/navbar' %></nav>
  <div class="container">
    <div class="row">
      <div class="col-md-11 col-md-offset-1">
        
      
        <%= yield %>
      </div>
    </div>
  </div>
  

</body>
</html>

app/views/statics/experience.html.erb
<div id="experience">
  <p><h3>Act - Dic 2013 Web and Desktop Developer in Joca Ingenería y Construcciones</h3></p>

  <p>
    <ul>
      <li>Design <%= link_to 'http://www.joca.es' , 'http://www.joca.es' %> (php, jquery, css) </li>
      <li>Intratet for the company (Ruby on Rails, jquery, bootstrap, css)</li>
      <li>App for the company manage (.Net) </li>
      <li>Maintece of virtual machines in Esxi </li>
    </ul>
  </p>

  <p><h3>Dic 2013 - Sep 2010 Deputy manager of the computer department in Area10</h3></p>

  <p>
    <ul>
      <li>Design and maintenance of the company web site and applications</li>
      <li>Development using C++ of the company management application</li>
      <li>Creation of the control module to integrate  the management  application and the database (.NET)</li>
      <li>Maintenance of the web server (Apache), database (Firebird), and virtualization environments (Vmware)</li>
      <li>Improvements to  the web application to support  tablet devices</li>
      <li>Improvement and development of the database (Firebird SQL)</li>
      <li>Management of the company network</li>
      <li>Community management and launch of  campaigns  for several clients of the company  in Facebook  and Twitter</li>
      <li>Creation of reports under Report Manager for other departtments of the company</li>
      <li>Maintenance and moderation of the CiscoWebex account</li>
    </ul>
    
  </p>

  <p><h3>Sep 2010 - Ago 2007 Founder of the company Informática y redes Inteclu SL, Badajoz</h3></p>
  <p>
    <ul>
      <li>Advice and service to businesses and individuals</li>
      <li>Design and installation of business networks</li>
      <li>Repair Hardware and Software related problems</li>
      <li>Sales of computer equipment</li>
    </ul>
  </p>
</div>

app/views/statics/microapps.html.erb
<div id="microapps">
  <h2>Words and Character Counter</h2>
  <p>
    <ul>
      <li>Words: <span id="words">0</span></li>
      <li>Characters: <span id="characters">0</span></li>
    </ul>
  </p>
  <p>
    Write your text here:
  </p>
  <textarea id="text" class="form-control" rows="6"></textarea>
</div>

app/views/statics/skills.html.erb
<table class="table">
  <tr>
    <th>Type</th>
    <th>Description</th>
  </tr>
  <tr>
    <td>
      Computer Skills:
    </td>
    <td>
      <ul>
        <li>Knowledge of several program languages:  Java, C, C++, .NET, Php, Ruby  and   Frameworks like JQuery and Rails</li>
        <li>Design and maintenance of databases: MySQL, Firebird  SQL and Microsoft Access</li>
        <li>Deep  knowledge of the Microsoft Windows operating system, and advanced knowledge of  GNU / Linux (desktop and server installations) and OS X.</li>
        <li>Advanced knowledge of hardware.</li>
      </ul>
    </td>
  </tr>
  <tr>
    <td>
      Personal Skills:
    </td>
    <td>
      <ul>
        <li>Capacity to organizacition and planification.</li>
        <li>Orientation to results</li>
      </ul> 
    </td>
  </tr>
  <tr>
    <td>
      Others: 
    </td>
    <td>
      <ul>
        <li>Great  learning capacity,  adaptation  and absolute predisposition to do courses and training to improve my skills.</li>
        <li>Great facility to work in teams</li>
        <li>Spanish driver's licenses A, B and own vehicle</li>
      </ul>
    </td>
  </tr>
</table>
  

  


  